title:  Pedro Piñera
description: Software Engineer at Shopify where I build tools for Mobile Developers (mostly in Ruby). I'm an open source who likes to share their experiences, learnings and work. When I'm not coding Ruby or Rails, you can find me playing with Swift.
head_tags: [ppinera, pedro pinera, ios developer, mobile developer, tuist, shopify, ruby, pedro piñera]
locale: en_US
markdown: kramdown
highlighter: rouge
url: https://ppinera.es
permalink: date
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - emoji_for_jekyll
  - jekyll-gist
  - jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 10
  title: 'Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
collections:
  posts:
    output: true
  galleries:
    output: true
repository: https://github.com/pepibumur/pepibumur.github.io
author:
  name: Pedro Piñera
  avatar: others/bio-photo.jpg
  bio: "Software Engineer at Shopify. Open source enthusiastic and running aficionado"
  email: "pedro@ppinera.es"
  twitter: "pepibumur"
  soundcloud: "ppinera"
  spotify: pepibumur
  bing-verify:
  github: "pepibumur"
  stackoverflow: "963511/pedro-piñera-buendia"
  speakerdeck: pepibumur
  dev: pepibumur
  linkedin: pedro-piñera-buendia-9765a9125
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "test", "spec", "package.json", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
