title:            Pedro Pi単era
locale:           en_US
permalink:   date
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - emoji_for_jekyll
  - jekyll-gist
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
repository: https://github.com/pepibumur/pepibumur.github.io
owner:
  name: Pedro Pi単era
  avatar: others/bio-photo.png
  bio: "Software Engineer and Open Sourcer"
  email: "pepibumur@gmail.com"
  twitter: "pepibumur"
  google:
    plus: "PedroPi単eraBuendia"
    analytics: UA-3325566-3
    verify: aEqj73Nc7NEwi7EjfpLlUhdeh9X3_IGO-7NyqBDSspk
    ad-client:
    ad-slot:
  bing-verify:
  github: "pepibumur"
  stackoverflow: "963511/pedro-pi単era-buendia"
  speakerdeck: pepibumur

include: [".htaccess"]
exclude: ["lib", "webpack", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
